lang: en
title: GR Host
theme: jekyll-theme-minimal
tagline: Enabled Growth
description: "Honest Web Hosting"
author: Matt Faulkner
#baseurl: "https://gr-host-pages.pages.dev/"
url: "https://www.grhost.net"
permalink: pretty
favicon: /assets/img/favicon.ico
logo: /assets/img/logo_color.png


plugins:
  - jekyll-sitemap 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme